DROP TABLE items IF EXISTS;
DROP TABLE invoices IF EXISTS;
DROP TABLE products IF EXISTS;
DROP TABLE customers IF EXISTS;

CREATE TABLE customers(
	id INTEGER PRIMARY KEY, 
	first_name VARCHAR(20) NOT NULL, 
	last_name VARCHAR(30) NOT NULL, 
	street VARCHAR(50) NOT NULL, 
	city VARCHAR(25) NOT NULL
);

CREATE TABLE products(
	id INTEGER PRIMARY KEY, 
	name VARCHAR(30) NOT NULL, 
	price DECIMAL NOT NULL
);

CREATE TABLE invoices(
	id INTEGER PRIMARY KEY,
	customer_id INTEGER NOT NULL, 
	total DECIMAL NOT NULL, 
	FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE items(
	id INTEGER PRIMARY KEY,
	invoice_id INTEGER NOT NULL, 
	item_id INTEGER NOT NULL, 
	product_id INTEGER NOT NULL, 
	quantity INTEGER NOT NULL, 
	cost DECIMAL NOT NULL, 
	FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE, 
	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);